### ISSUE TITLE
Analyze (and fix) warnings when computing peaks

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#381]
We typically get some RuntimeWarnings when computing and writing peaks. Should look into their origin, and if we should care about it or not.

![Screenshot 2024-06-05 163537](https://github.com/Karsa-Oy/Mascope/assets/79190195/d8246ad6-4fed-4fa1-ad1c-f60b15f9e764)
![Screenshot 2024-06-05 163511](https://github.com/Karsa-Oy/Mascope/assets/79190195/ac8564a8-65cb-4b93-8932-7d1b57d40dec)

**Comment by ghost** [comment]
The warnings arise during the calculation of parameter uncertainties and correlations. Specifically, in the calculation of the standard error as the square root of the corresponding diagonal element of the covariance matrix, which represents the variance of the parameter.
```
Traceback (most recent call last):
~Mascope\libraries\mascope_lib\mascope_lib\peak.py", line 426, in fit_peaks
    fit = minner.minimize(method="least_squares", max_nfev=max_iter)
~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 2330, in minimize
    return function(**kwargs)
~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 1578, in least_squares
    self._calculate_uncertainties_correlations()
~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 802, in _calculate_uncertainties_correlations
    par.stderr = np.sqrt(self.result.covar[ivar, ivar])
RuntimeWarning: invalid value encountered in sqrt
```
The presence of invalid values in the covariance matrix elements likely indicates issues with the fitting process or the data. This can be poor model fit, inadequate data quality, or inappropriate parameter bounds/initial guesses.

However, I don't think that it is concerning because the fit still converges and we don't hit the number of iterations limit. Besides that, the sectors triggering warnings look more like noise:

![image](https://github.com/Karsa-Oy/Mascope/assets/162983707/47493bab-9db3-4401-9f6f-9c4e8b5f9bc3)

There are 2 ways to proceed:
1. Figure out how to filter out bad sectors
2. Suppress invalid value warnings specifically in the fitting:
```
with np.errstate(invalid='ignore'):
    fit = minner.minimize(method="least_squares", max_nfev=max_iter)
```

Test file: KLTOF1_2024.03.26_14h01m33s_FILTER_BACKGROUND_+
Full log: [log.txt](https://github.com/user-attachments/files/15983583/log.txt)

**Comment by oskarsari** [comment]
> The warnings arise during the calculation of parameter uncertainties and correlations. Specifically, in the calculation of the standard error as the square root of the corresponding diagonal element of the covariance matrix, which represents the variance of the parameter.
> 
> ```
> Traceback (most recent call last):
> ~Mascope\libraries\mascope_lib\mascope_lib\peak.py", line 426, in fit_peaks
>     fit = minner.minimize(method="least_squares", max_nfev=max_iter)
> ~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 2330, in minimize
>     return function(**kwargs)
> ~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 1578, in least_squares
>     self._calculate_uncertainties_correlations()
> ~mascope-notebooks-SW-4yc8V-py3.10\lib\site-packages\lmfit\minimizer.py", line 802, in _calculate_uncertainties_correlations
>     par.stderr = np.sqrt(self.result.covar[ivar, ivar])
> RuntimeWarning: invalid value encountered in sqrt
> ```
> 
> The presence of invalid values in the covariance matrix elements likely indicates issues with the fitting process or the data. This can be poor model fit, inadequate data quality, or inappropriate parameter bounds/initial guesses.
> 
> However, I don't think that it is concerning because the fit still converges and we don't hit the number of iterations limit. Besides that, the sectors triggering warnings look more like noise:
> 
> ![image](https://private-user-images.githubusercontent.com/162983707/343035273-47493bab-9db3-4401-9f6f-9c4e8b5f9bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODM1MTAsIm5iZiI6MTcxOTQ4MzIxMCwicGF0aCI6Ii8xNjI5ODM3MDcvMzQzMDM1MjczLTQ3NDkzYmFiLTlkYjMtNDQwMS05ZjZmLTljNGU4YjVmOWJjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMDEzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzE1YTZiZjBkMzcyMWM5MTUwNzA3OWMzZmJkNTM5NTYzZGQyODVhZjMzYmM5MTEyYmM0NzllOWFmYjQ4N2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f7Amr3G2Ux6r8jGezkTZrbyz9QZHUZ2FnHWuAf7mGgg)
> 
> There are 2 ways to proceed:
> 
> 1. Figure out how to filter out bad sectors
> 2. Suppress invalid value warnings specifically in the fitting:
> 
> ```
> with np.errstate(invalid='ignore'):
>     fit = minner.minimize(method="least_squares", max_nfev=max_iter)
> ```
> 
> Test file: KLTOF1_2024.03.26_14h01m33s_FILTER_BACKGROUND_+ Full log: [log.txt](https://github.com/user-attachments/files/15983583/log.txt)

Created a follow-up issue based on suggestion 1: #420
