### ISSUE TITLE
Use logging instead of print in backend console

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#383]
To clean up backend console log , use a logging module, for example [loguru](https://github.com/Delgan/loguru), with different logging levels (debug, error) instead. Pay attention to subprocess logging

**Comment by ixxie** [comment]
Our upcoming `mascope` command uses [Typer](https://typer.tiangolo.com/) for implementing the CLI, which in turn uses a great library called [Rich](https://rich.readthedocs.io/en/stable/introduction.html)  for styled printing in the terminal. Rich includes a [logging handler](https://rich.readthedocs.io/en/stable/logging.html) for the Python standard [`logging`](https://docs.python.org/3/library/logging.html) module. The quick and immediate benefit is enable simple formatting for our log messages:
```python3
log.error("[bold red]Server is shutting down![/]")
```

Other interesting possibilities:
- [Tables](https://rich.readthedocs.io/en/stable/tables.html) for debugging data in general
- [Tree views](https://rich.readthedocs.io/en/stable/tree.html) for debugging the target and sample hierarchies in the backend
- [Progress bars](https://rich.readthedocs.io/en/stable/progress.html) for tracking our processes

## Proposal

I argue we should:
1. Use the standard logging module for now, since its widely supported, exploring [possible drop-in replacements](https://github.com/microsoft/picologging) in the future
2. Use Rich to allow us some nicer formatting
3. Implement our logging in a shared `runtime` library - the same one we implemented configuration in - so it can be shared across all of our Python packages

**Comment by ixxie** [comment]
Implemented!
