### ISSUE TITLE
Synthesize signal to evaluate peak fitting

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#409]
To be able to measure peak fitting performance, should synthesize signal segments to fit.

**Scenario 1:**
Ideal peak shape and resolution function.

Vary:
- number of peaks
- position of peaks
- intensity of peaks
- (peak shape)
- (resolution)

**Scenario 2:**
Distorted signal (random noise, skewed peak shape). Use peak shape as a probability distribution and run tests using different numbers of samples.

Vary:
- noise level
- skewness of peaks (difference of synthesized peak compared to assumed peak shape)

**Metrics:**
Measure fit goodness by:
- R^2 of the fit
- m/z error of peaks
- intensity error of peaks
- number of missed/extra peaks

**Comment by oskarsari** [comment]
Reference paper:
https://amt.copernicus.org/preprints/7/12617/2014/amtd-7-12617-2014.pdf

**Comment by ghost** [comment]
I started with Scenario 1 (or Orbitrap scenario). The initial task was to generate spectrum segments.
Apparently, this is way less efficient compared to the generation of the whole spectrum for several reasons:
1. Precomputing the whole range of m/z values in one run is faster than computing it for each sector
2. We don't have to figure out the sector length, it comes naturally after segmentation of the whole spectrum.
3. We don't have to put overcomplicated limitations on a peak position within a sector so that the whole peak would fit in the sector (as we see it in real orbitrap spectra).
4. We can take advantage of vectorized operations while generating peak parameters. It makes calculations way faster.

I have analyzed histograms from the real spectrum to determine the parameters' distribution. I assume the following:
- The m/z grid is precomputed based on the resolution function.
- The resolution function coefficient for Orbitrap is random in the range of 1.725e6±5%.
- Peak heights are distributed as a power probability density function (pdf) $P(x, a) = a \cdot x ^ {a-1}$ implemented in `numpy.random.Generator.power`.
- Peak positions are distributed uniformly and obtained with `numpy.random.Generator.uniform`.
- Peak shapes are assumed to be purely Gaussian.
- The number of peaks is chosen arbitrarily.

Implementing all that, we have spectra looking very close to what we observe in real Orbitrap data. I generated a spectrum with 100 peaks and tried to fit it with an imperfect peak shape and resolution function using our common Mascope fitting routine.

**Comment by ghost** [comment]
A spectrum for Scenario 2 (or TOF scenario) was generated using the same approach as in the case of Scenario 1 with several exceptions:
1. The peak shape is a skewed Gaussian instead of a purely Gaussian.
2. The Poisson noise was added to the final signal.
3. The spectrum was segmented by integer m/z values +- dmz, where dmz=0.5.
