### ISSUE TITLE
Replace lmfit with scipy to compute peak fitting

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#422]
Evaluate potential performance gain and implement if useful

**Comment by ghost** [comment]
To quickly check if it's worth it,  I decided to fit the exponential function
```
def model(x, a, b):
    return a * np.exp(-x / b)
```
I generated some random data with 
```
x = np.linspace(0, 10, 100)
y = 3.0 * np.exp(-x / 2.0) + np.random.normal(size=x.size)
```
Scipy implementation: 
```
popt, pcov = curve_fit(model, x, y, p0=(1, 1))
```
Lmfit implementation: 
```
model = Model(model)
popt, pcov = curve_fit(model, x, y, p0=(1, 1))
result = model.fit(y, x=x, a=1, b=1)
```
Timing looks promising:
- Scipy: 6.38 ms
- Lmfit: 29.8 ms

**Comment by ghost** [comment]
...but the problem is that we need to fit a custom objective function with lots of bounds. And implement this scenario in pure Scipy leads to creating the same overhead as we have in lmfit. Later I found, that the common approach is to use Scipy routines for basic minimization operations and lmfit for advanced peak fitting.

Minor improvements in `peak.py`, such as preallocating arrays, vectorization, pre-computation, changing data types, etc., allowed for decreasing fitting time by 20-25% (from 12.21 ± 1.54 to 8.14 ± 0.11 seconds with files tested). 

I also tried to optimize the objective function itself, `gen_peak`. The algorithm calls it many times and even a small improvement could drop the processing time. We did everything possible from the Python side so I wrote a small C# module for peak generation. The generation was indeed ~10 times faster. However, the overhead caused by multiple `ClrFunction.__call__` during the fitting (the interaction between Python and C#) annihilates the speed gain.

My conclusion: I don't think significant speed improvement is achievable with the current fitting approach.
