### ISSUE TITLE
Research FastAPI user authentication and authorization

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#457]
Research the suitability of FastAPI built-in authentication tools for user authentication and authorization in Mascope

**Comment by philip-chernonog** [comment]
The  authentication and authorization method largely depend on our hosting and deployment strategy. Since we are currently opting for Virtual Private Server (VPS) hosting, it may be better to implement a self-hosted solution that aligns with our infrastructure.

**Deployment specifics:**

- FastAPI backend
- Nginx with HTTPS as a reverse proxy
- Docker containers for deployment
- Linux servers on a VPS
- Small user base per server (~10–20 users), including roles like super developers and admins, etc.

**Option 1: Using native FastAPI authentication features**

We can leverage FastAPI's built-in authentication mechanisms, such as [OAuth2 with JWT Tokens](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/), to implement custom authentication and authorization. This involves issuing JWT tokens upon user login, securely storing them (e.g., in HTTP-only cookies), validating tokens on protected routes, and embedding user roles like super developers and admins, etc. For SSO integration with Google, we can implement the OAuth2 flow as outlined in [FastAPI Google Single Sign-On (SSO)](https://itnext.io/fastapi-google-single-sign-on-sso-47454e2e2859), which includes registering our app with Google, handling redirects, and processing user information. While this approach offers maximum control, it is time-consuming and complex, especially for features like password resets and ensuring compliance with security best practices. Therefore, utilizing libraries that seamlessly integrate with FastAPI could be benfitial. 

**Option 2: Using [FastAPI Users](https://fastapi-users.github.io/fastapi-users/latest/) library**

[FastAPI Users](https://github.com/fastapi-users/fastapi-users) is a user management library that provides authentication and authorization functionalities for FastAPI applications. It supports multiple authentication backends, including OAuth2, which is essential for Single Sign-On (SSO) with providers like Google and Microsoft.

By integrating FastAPI Users, we can leverage features such as:

- **integration with SQLAlchemy and SQLite:**
    - The library works natively with SQLAlchemy, allowing us to define user models that integrate with our existing SQLite database setup.
    - Customizable user models let us add specific fields like roles (e.g., super developers, admins), and the library manages database operations for user creation, retrieval, and updates through built-in user manager classes.
    - Facilitates password hashing, verification, and lifecycle events (e.g., user creation or update hooks).
- **Dependency injection and route protection:**
    - Provides ready-made dependency classes for injecting authenticated users or current user roles directly into route handlers.
    - Simplifies endpoint protection by enforcing access restrictions, requiring specific roles, or authenticated users, using decorators or route dependencies.
- **SSO Integration with Google:**
    - Offers [[OAuth2 authentication](https://fastapi-users.github.io/fastapi-users/latest/configuration/oauth/) support via the [HTTPX OAuth library](https://frankie567.github.io/httpx-oauth/), an async implementation of OAuth, theoretically simplifying the integration of SSO with providers like Google or Microsoft.
    - For SSO with Google, developers set up OAuth client credentials (client ID and secret) and redirect URIs.
    - FastAPI Users facilitates handling the OAuth2 authorization flow, including user consent redirects and callback processing, but requires us to implement logic for user account creation or linking after successful OAuth2 authentication.

**Option 3: Using [Authlib](https://docs.authlib.org/)**

[Authlib](https://docs.authlib.org/) is a library for building OAuth and OpenID Connect clients and servers. It is a lower-level library compared to FastAPI Users, offering fine-grained control over authentication mechanisms and protocols.

- **Features and integration:**
    - Supports OAuth 1.0, OAuth 2.0, and OpenID Connect, enabling integration with various identity providers for SSO, including Google and Microsoft.
    - More f**lexible** for implementing custom authentication flows and specific security requirements.
    - **Integration with FastAPI:**
        - Can be integrated into our FastAPI application but [requires manual setup.](https://docs.authlib.org/en/latest/client/fastapi.html)
        - Need to implement the OAuth2 flow, token management, and user session handling.
        - Offers the ability to customize every aspect of the authentication process.
- **Considerations:**
    - Requires more effort to set up compared to higher-level libraries like FastAPI Users.
    - Devs need familiarity with OAuth protocols and Authlib's API.

**Option 4: Using [SuperTokens](https://supertokens.com/docs/)**

[SuperTokens](https://supertokens.com/docs/) is an open-source authentication solution offering features like email/password login, social login, passwordless authentication, and session management. It can be self-hosted on our VPS, aligning with our deployment strategy.

- **Features and integration:**
    - **Alignment with FastAPI backend:**
        - **Middleware inegration:** Provides middleware for FastAPI to handle authentication and session verification.
        - **Route protection:** Use dependency injection or decorators to secure endpoints, making it easier to enforce authentication within FastAPI routes.
- **Working with SQLAlchemy and SQLite⚠️(Updated) **
  - **SQLite3 for development only⚠️**
    - Although **SQLite** is mentioned in SuperTokens' documentation and used internally for [development and testing purposes](https://community.supertokens.com/t/430704/hi-i-m-curious-if-there-has-been-any-thoughts-of-supporting-#b7c39f15-fdd7-49e8-8e45-88cc2b828cac), it is [not suitable for production](https://supertokens.struct.ai/2J22d6d) environments. In production, SuperTokens [requires ](https://supertokens.com/docs/thirdpartyemailpassword/scalability#database-scalability) PostgreSQL or MySQL for handling user and session data at scale.
    - **Managing 2 databases:**
        - One option is to manage two databases: using **SQLite** for the application's models and **PostgreSQL/MySQL** for SuperTokens' authentication data. However, this approach can become verbose and complex, as we would need to manually sync user-related data between the two databases, leading to additional development overhead and potential data consistency issues.
    - **Migration to PostgreSQL/MySQL:**
        - One more point to considering a **migration to PostgreSQL**. This would allow compatibility with SuperTokens' production-ready infrastructure. [DEV Community](https://dev.to/supertokens/how-to-connect-supertokens-to-a-mysql-or-to-a-postgresql-database-2bbo)
    - **SSO Support:**
        - Enables social login integration with providers like Google.
        - Support for Microsoft accounts may require additional configuration.
    - **Customizable UI components:** Offers pre-built authentication components that can be tailored to our application's design.
    - **Deployment:**
        - Requires running a separate SuperTokens service, can be containerized using Docker
    - **Documentation:** Provides detailed documentation and example projects for FastAPI and Vue integrations.
- **Considerations:**
    - Given that SuperTokens does not support SQLite for production use, and considering our current reliance on SQLite3 with SQLAlchemy, SuperTokens may not be a viable option without significant changes to our database infrastructure. It would be advisable to focus on alternatives like FastAPI Users or custom authentication solutions that are compatible with SQLite in production or to consider the database migration. 
    - **Additional infrastructure:** Adds complexity by introducing an additional service to manage and maintain.

**Comment by oskarsari** [comment]
Next steps laid out in a [follow-up issue](https://github.com/Karsa-Oy/Mascope/issues/545)
