### ISSUE TITLE
Evaluate peak fitting performance on synthesized spectra

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#494]
Produce figures and text for the Mascope manuscript.

**Comment by ghost** [comment]
The task was to generate artificial spectra with known ground truth (GT), fit them, plot results, and compare fitted peaks with GT.

While making figures, we noticed the issue with fitted peak positions. Fitted values were falling into "bins" around GT. @oskarsari assumed the fitted values are somewhere rounded to the m/z grid nodes, however, I didn't find evidence. I noticed that: 
1. Somehow TOF looks way better than Orbi
2. The ppm error between ground truth and fitted peaks strangely was within the difference between float32 and float64

I concluded that I lacked precision somewhere. And I found out that the problem was in the peak shape. At some point, I changed the peak shape precision to np.float32, because it made computations much faster. We usually don't see such overlaps in experimental spectra and have no GT. I didn't notice something went wrong. After checking the spectra with known GT, it becomes obvious that this change of the peak shape precision must be reverted.

All the spectra below are obtained with the peak shape precision of (numpy) float64.

**Comment by ghost** [comment]
## Overlap effect

I generated and fitted a spectrum segment with 5 peaks around m/z=200 Th. The peaks were evenly spaced, and the distance was set to i*resolution, where i - is a multiplier that varied with a step of 0.1. 

 ### Orbitrap
The fitting loses consistency at i=0.9, likely due to the symmetric peak shape.

![Orbi, change distance](https://github.com/user-attachments/assets/ac7af985-557b-403f-b459-f55fa6329b63)

### TOF
The peak fitting starts to fail at i=0.6...0.7.

![TOF, change distance](https://github.com/user-attachments/assets/c49621c1-6cc2-4c0a-be44-fc66b297474d)

**Comment by ghost** [comment]
## More statistics

We needed to estimate how the peak fitting algorithm performs overall. Artificial spectra segments were generated, with peaks evenly spaced with a distance of 0.5\*resolution, 1\*resolution, and 2*resolution around 200 Th. Peak heights were generated in the range of 1e2...1e6 counts. The m/z errors in ppm and height errors in % (absolute percentage error) were collected for 1000 spectra generations and plotted to see error distributions. The number of fitted peaks was also recorded to estimate under-/overfit.

**Comment by ghost** [comment]
### Orbitrap
![orbi_half](https://github.com/user-attachments/assets/40939e0e-0319-4d9c-aaba-da99d597ca21)
![orbi_one](https://github.com/user-attachments/assets/16f837af-7435-425e-b447-7fb20759eb64)
![orbi_double](https://github.com/user-attachments/assets/ab94def0-7bc5-48d0-8e45-ed03589afe66)

**Comment by ghost** [comment]
### TOF
![tof_half](https://github.com/user-attachments/assets/e7da298f-bc09-4b99-9d8b-007a06a5a3ed)
![tof_one](https://github.com/user-attachments/assets/f06e5caa-75a3-4ed9-b5da-b5f10faa5942)
![tof_double](https://github.com/user-attachments/assets/3e6c931a-c7f7-4e42-ad84-0d68272650a0)

**Comment by ghost** [comment]
First draft of the figure for the manuscript, the peaks are generated based on the SI of [this manuscript](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017JD026930).

<img width="3249" alt="peak_fit_results" src="https://github.com/user-attachments/assets/1a13c885-6dec-4e7c-8bba-c09f6152d07f">
