### ISSUE TITLE
Validate "peak reliability score"

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#516]
Let us define _peak reliability score_ as `1 - (peak area / peak intersection)`, where `peak intersection` is the area where peak intersects with other peak(s).

On synthesized spectra, see if the proposed metric correlates with m/z error and intensity error of fitted peaks.

**Comment by ghost** [comment]
I tried to look at the correlations of the reliability score in cases when the heights and positions are predefined. I compared several distances between peaks, 0.5, 1, and 2 mz/resolution. I don't see any meaningful trend there.
![preset_pos_same_heights_tof](https://github.com/user-attachments/assets/09c9662b-fe54-4fc0-849b-0daae527bd15)

**Comment by ghost** [comment]
I tried to add the distance between peaks as a factor affecting the reliability score. The idea was that if the peaks were too close, the reliability score would decrease. That didn't improve the score much. The correlation with m/z and height errors still jumps from -0.1 to -0.9 if I generate random positions and heights.

**Comment by ghost** [comment]
I plotted the reliability score vs other parameters. I didn't notice anything I could describe with a function. A couple of examples (however, the distribution is very much different from one generation to another):
![image](https://github.com/user-attachments/assets/c3050283-206a-4433-8d9b-ad9caa83503c)
![image](https://github.com/user-attachments/assets/77343833-0f30-4cdf-acf5-a72ce525839b)

**Comment by ghost** [comment]
Lmfit estimates parameter uncertainties as standard errors, based on their variation during the fitting process. It could be a robust estimation of the goodness of the fitting parameter. The problem was that lmfit returned None for the standard error. I figured out that it's because we pass peak shape as a dictionary instead of numpy arrays to the residual function supposed to be minimized. After fixing this, I got standard errors but not in all cases, lmfit still skips error estimation for some of the fits.

I checked the correlation of these standard errors with mz_error and height_error which I calculated for the fitted peaks compared to ground truth. The correlation of mz stderr with the mz error in ppm was pretty random, height errors did not correlate at all. The correlation of the reliability score with m/z errors in ppm and heights in % was higher in all cases.

**Comment by ghost** [comment]
Our reliability score only takes into account the overlap. However, this is not the only parameter affecting the fit's quality. The quality also depends on the signal-to-noise ratio, the relative height of peaks, resolution, and, I don't know, the goodness of the initial guess. From the correlation with m/z and height errors, the overlap-based reliability score is likely insufficient as a general estimation.

**Comment by ghost** [comment]
I reconstructed spectra from [this dataset](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017JD026930) to have a real experimental signal with known ground truth. Then I did more tests with other metrics.

**Comment by ghost** [comment]
I hypothesized that the residual distribution would be random for properly fitted spectra chunks.

I performed [Shapiro-Wilk](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test) and [Anderson-Darling](https://en.wikipedia.org/wiki/Anderson%E2%80%93Darling_test) tests on the residual histogram and found nothing.

Then I applied [autocorrelation function](https://en.wikipedia.org/wiki/Autocorrelation) to see any correlations in residuals within one chunk. That would talk to the non-random distribution but I detected nothing.

Further, I used [Runs Test](https://www.ibm.com/docs/en/spss-statistics/30.0.0?topic=tests-runs-test). This method showed that all my chunks are non-random. At this point, I decided to apply the approach to truly random `np.array`. The method worked fine. Only after that, I plot all the residual chunks to inspect them visually - and yes, none of them are random. One typical example:

![image](https://github.com/user-attachments/assets/d0da35d2-761f-4aed-8cf0-101260993090)

So, the hypothesis was dismissed.

**Comment by ghost** [comment]
I decided to check $R^2$ once again. I remember it failed to detect all bad cases before. But I found a bug - because of spectrum scaling before the fitting, the $R^2$ produced by `lmfit` was incorrect or, better say, imprecise. I restored the total fitted signal from the fitted peaks and calculated residuals myself. That helped to get better results.

![stderr_of_residuals](https://github.com/user-attachments/assets/b006f4ac-3162-45cb-b276-04c7fec512c7)

**Comment by ghost** [comment]
Some examples of what I call a bad fit that could be detected by looking at $R^2$.

![r_squared_big_success](https://github.com/user-attachments/assets/ff748b2c-6587-45da-80bb-93b141d85bfc)

**Comment by ghost** [comment]
I set the threshold to 0.9999 but this is probably an overshoot.

<img src=https://github.com/user-attachments/assets/3bd6517f-9fa1-459e-b943-25d43f991c7b width=450/>

**Comment by ghost** [comment]
These are the examples where $R^2$ couldn't help.

<img src=https://github.com/user-attachments/assets/ccca1490-fc97-4e77-ad9b-3eb96aa6aba3 width=500/>

**Comment by ghost** [comment]
I have also calculated the normalized Residual Sum of Squares (RSS) for each chunk. Chunks with significantly higher RSS values may indicate poor fits. The method massively overestimated outliers and was hard to tune.

Calculating the mean standard deviation of residuals between all chunks worked much better. However, filtering out chunks with a standard error higher than the mean error didn't show anything new compared to $R^2$. 

All the results above are relevant for Orbitrap spectra and will now be checked for TOF.

**Comment by ghost** [comment]
The ability of $R^2$ to detect even minor inconsistency with a fitting was confirmed on a larger subset of restored experimental spectra, including TOF. 

![more_examples](https://github.com/user-attachments/assets/2b4a82c2-9b63-4e7a-a9df-36953c651856)
