### ISSUE TITLE
Design fine-grained user access rights

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#571]
Collect requirements and designed more fine-grained permission schema. For example, do we need per-user workspaces?

**Comment by ixxie** [comment]
If I understand correctly, this is about designing **authorization**:

![image](https://github.com/user-attachments/assets/690a3f57-c3b4-4ed7-ac25-fe212370599b)

The (by far) most common model for authorization is Role-based Access Control (RBAC), which is modeled as *Roles* getting certain *Permissions* associated with them, and then a *User* getting assigned a *Role* to some *Resource*:

![image](https://github.com/user-attachments/assets/e9e8c132-f645-43a6-9cd9-e69bb4889ef7)

## Mascope Authorization RBAC Model

In my experience the common roles necessary are:
- **Owner** - the main Admin, [primus inter pares](https://en.wikipedia.org/wiki/Primus_inter_pares), can add/remove other admins
- **Admin** - has all permissions of an Editor and can also add/remove Editors/Guests from the resource as well as manage some resource-specific settings
- **Editor** - has read and write access to the resource's contents
- **Guest** - has read access to the resource's contents but no write access

Of course, we should probably bike-shed the names.

In Mascope's case the most obvious resources to assign roles to are:
- **App** - global context with *Owner*, *Admin*, *Editor* and *Guest* roles
- **Workspace** - scoped context with *Owner*, *Admin*, *Editor* and *Guest* roles

For more granular control, *Batch* would also be considered as a resource, but I will exclude it here since an MVP doesn't require it.

The relationship between these two resource-roles should be minimal:  *App Admins* (and by extension, *App Owners*)  have *Workspace Owner* level permissions for *all Workspaces* and can assign additionally assign *Workspace Owner* roles to *specific Workspaces*.

**Comment by philip-chernonog** [comment]
The first stage includes the following issues:
- #557
- #646
- #645
