### ISSUE TITLE
Experiment with voilà for instrument function evaluation notebook

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#631]
As a quick way to let users evaluate the fitted instrument functions, we could potentially serve a notebook to them using [_voilà_](https://voila.readthedocs.io/en/stable/index.html).

Let's make an experiment how this could work, and then decide whether it's worth pursuing to deploy it as part of Mascope.

**Comment by ghost** [comment]
## A quick summary

**Pros:**
- We can make web dashboards using Jupyter and its widgets, no new skills are required.
- Voila hides the code cells and only displays the output, making it suitable for sharing with non-technical users interested in the results rather than the code.
- Voila can be easily deployed.
- Being open-source, Voila is free to use and benefits from community contributions. We can tweak something if needed. 

**Cons:**
- Customisation is limited compared to other frameworks like DASH or Gradio.
- Performance is not that great.
- Since Voila executes the notebook on the server, there can be security concerns.

**Conclusion:**
I see Voila as a suitable option for the quick deployment of simple web dashboards and integration of them into Mascope.
