### ISSUE TITLE
Reverse engineer Orbitrap TIC calculation

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#662]
How to calculate the TIC for Orbitrap, and get a number which is close enough to what we get in Tracefinder

**Comment by ghost** [comment]
I installed the Thermo Freestyle application to have a TIC value reference. Then I calculated TICs in several ways. I used `RawFileReader` to read the file directly and Mascope libs to read a converted file. Since Freestyle shows TIC for each time scan, I compared values for the first one.

    - Freestyle (reference value):							2.892e+07
    
    - RawFileReader
        - Peak height sum (find_peaks from scipy used):		2.834e+07
        - Sum of centroids (=peak heights):					2.892e+07
        - Sum of all counts:								1.123e+08
        - Signal integral / median(FWHM):					2.863e+07
       
    - Mascope
    - Peak height sum (find_peaks from scipy used):			2.834e+07
    - Sum of all counts:									1.123e+08
    - Signal integral / median(FWHM):						2.815e+07

From the results, we can conclude that TIC in Freestyle is a sum of fitted peak heights. This makes sense since we consider one peak to be one species. The problem is that we wouldn't like to fit all the peaks every time. In the results above I added two approximations. First, quickly find and sum peaks with `find_peaks` function from `scipy.signal`. Second, calculate the "signal integral" and divide it by the median FWHM. More details on the second approach:

$$ TIC = \frac{\sum{H} \cdot mz_{diff, median}}{FWHM_{median} \cdot 1.064} $$

where $\sum{H}$ is a sum of counts, $mz_{diff, median}$ - median mz step. Median FWHM:

$$FWHM_{median} = \frac{mz_{median}}{R(mz_{median})}$$

where $mz_{median}$ - median mz value, $R(mz_{median})$ - resolution at the median m/z value.

The error of approximations is <5% (2% for `find_peaks` and 1% for the integral/FWHM in the considered case).

**Comment by ghost** [comment]
If we look at the sum signal, TIC via `find_peaks` shows a closer result.

    sum of centroids, RawFileReader:			7.956e+09
    find_peaks, Mascope:						7.720e+09
    signal integral / median(FWHM), Mascope:	9.156e+09

Probably, a higher value in the case of signal integral / median(FWHM) is related to issue #610.
